language: php

php:
  - 7.1

before_script:
  - cp .env.example .env
  - npm install
  - composer self-update
  - composer install --no-interaction

script:
  - php artisan key:generate
  - vendor/bin/phpunit
  - npm run test

after_success:
  - [ "$TRAVIS_BRANCH" != "master" ] || curl -s "https://forge.laravel.com/servers/183115/sites/488203/deploy/http?token=$FORGE_TOKEN"

cache:
  directories:
    - vendor
    - node_modules
